dist: trusty
sudo: false
language: android
matrix:
  include:
  # ARM Android
  - env:
    - TARGET=arm-linux-androideabi
    - NDK_ARCH=arm
    - SIM_ABI=armeabi-v7a
    - SIM_TAG=android-24
    android:
      components:
      - build-tools-19.1.0
      - android-24
      - sys-img-armeabi-v7a-android-24
before_install:
- set -eo pipefail
- git clone https://github.com/dekalo-stanislav/android-ndk $HOME/android-ndk
- export ANDROID_NDK_HOME=$HOME/android-ndk
# Minimum API level is 21, as that's when getpagesize got introduced
- "$ANDROID_NDK_HOME/build/tools/make_standalone_toolchain.py --arch $NDK_ARCH --api
  21 --install-dir $HOME/toolchain"
- export PATH=$HOME/toolchain/bin:$PATH
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
- source ~/.cargo/env
install:
- rustup target add $TARGET
before_script:
- echo no | android create avd --force -n test -t $SIM_TAG --abi $SIM_ABI
- QEMU_AUDIO_DRV=none emulator -avd test -no-window &
- adb wait-for-device
- adb shell input keyevent 82 &
- mkdir .cargo
- echo "[target.${TARGET}]" >> .cargo/config
- echo "linker = \"${TARGET}-gcc\"" >> .cargo/config
- echo "ar = \"${TARGET}-ar\"" >> .cargo/config
script:
- cargo build --target=$TARGET
- cargo doc --target=$TARGET
- cargo test --target=$TARGET --no-run #--message-format=json | jq -r "select(.profile.test == true)
  #| .filenames[]" | xargs -I "{}" sh -c "adb push {} /data/local/tmp && adb shell
  #/data/local/tmp/$(basename {})"
after_success:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_52aad774d5b3_key -iv $encrypted_52aad774d5b3_iv
  -in ci/id_rsa.enc -out ci/id_rsa -d
- chmod 600 ci/id_rsa
- ssh-add ci/id_rsa
- cd target/$TARGET/doc
- git init
- git remote add origin "git@github.com:roblabla/binder"
- git checkout -b gh-pages
- git commit -am "Docs"
- git push --force origin gh-pages
